import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4 flex items-center justify-between">
          <h1 className="text-white text-xl">Parakeet</h1>
          <div>
            <Link href="/" className="text-white mr-4 hover:underline">Home</Link>
            <Link href="/about" className="text-white mr-4 hover:underline">About</Link>
            <Link href="/ask" className="text-white hover:underline">Ask</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
